/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SC_Init.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         
  * @details         Contains the MCU initialization function and its C file
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */

#include "SC_Init.h"	// MCU initialization header file, including all firmware library header files
#include "SCDriver_List.h"
#include "HeadFiles\SC_itExtern.h"


/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
/*************************************.Generated by EasyCodeCube.************************************/

/**
  * @brief MCU init
  * @note 
  * @param
  */
void SC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	SC_GPIO_Init();
	SC_OPTION_Init();
	SC_RCC_Init();
	SC_SYSTICK_Init();
	SC_TWI0_Init();
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief RCC init
  * @note 
  * @param
  */
void SC_RCC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_HXTCmd(DISABLE);
	RCC_LXTCmd(DISABLE);
	RCC_LIRCCmd(ENABLE);
	RCC_HIRCCmd(ENABLE);
	/*INTEN*/RCC_ITConfig(ENABLE);
	RCC_SYSCLKConfig(RCC_SYSCLKSource_HIRC);
	RCC_HCLKConfig(RCC_SYSCLK_Div1);
	RCC_APB0Config(RCC_HCLK_Div1);
	RCC_APB0Cmd(ENABLE);
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief system timer init
  * @note 
  * @param
  */
void SC_SYSTICK_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	RCC_Unlock(0xFF);
	RCC_SystickCLKConfig(RCC_SysTickSource_HCLK_DIV8);
	RCC_SystickSetCounter(16000);
	NVIC_SetPriority(SysTick_IRQn,0);
	RCC_SystickCmd(ENABLE);
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief custom OPTION init
  * @note 
  * @param
  */
void SC_OPTION_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	SC32F10xSx_NIO_Init();
	OPTION_LVRConfig(OPTION_LVR_4_3V);
	/*Init Struct*/OPTION_JTAGCmd(DISABLE);
	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_IFB,DISABLE);
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief nvic init
  * @note 
  * @param
  */
void SC_NVIC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief GPIO init
  * @note 
  * @param
  */
void SC_GPIO_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART0 init
  * @note 
  * @param
  */
void SC_UART0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART1 init
  * @note 
  * @param
  */
void SC_UART1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART2 init
  * @note 
  * @param
  */
void SC_UART2_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART3 init
  * @note 
  * @param
  */
void SC_UART3_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}
#if defined (SC32f12xx)

/**
  * @brief UART4 init
  * @note 
  * @param
  */
void SC_UART4_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief UART5 init
  * @note 
  * @param
  */
void SC_UART5_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}
#endif

/**
  * @brief Timer0 init
  * @note 
  * @param
  */
void SC_TIM0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer1 init
  * @note 
  * @param
  */
void SC_TIM1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer2 init
  * @note 
  * @param
  */
void SC_TIM2_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer3 init
  * @note 
  * @param
  */
void SC_TIM3_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer4 init
  * @note 
  * @param
  */
void SC_TIM4_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief Timer5 init
  * @note 
  * @param
  */
void SC_TIM5_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer6 init
  * @note 
  * @param
  */
void SC_TIM6_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief Timer7 init
  * @note 
  * @param
  */
void SC_TIM7_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief PWM0 init
  * @note 
  * @param
  */
void SC_PWM0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief LEDPWM init
  * @note 
  * @param
  */
void SC_LEDPWM_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief INT init
  * @note 
  * @param
  */
void SC_INT_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ADC init
  * @note 
  * @param
  */
void SC_ADC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief IAP init
  * @note 
  * @param
  */
void SC_IAP_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI0 init
  * @note 
  * @param
  */
void SC_SPI0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief SPI1 init
  * @note 
  * @param
  */
void SC_SPI1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}
#if defined (SC32f12xx)

/**
  * @brief SPI2 init
  * @note 
  * @param
  */
void SC_SPI2_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

#endif

/**
  * @brief TWI0 init
  * @note 
  * @param
  */
void SC_TWI0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*GPIOInit_PA05 Struct*/GPIO_InitTypeDef GPIOInit_PA05_Struct;
	GPIOInit_PA05_Struct.GPIO_Pin = GPIO_Pin_5;
	GPIOInit_PA05_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA05_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA05_Struct);/*SDA0B端口初始化*/
	/*GPIOInit_PA06 Struct*/GPIO_InitTypeDef GPIOInit_PA06_Struct;
	GPIOInit_PA06_Struct.GPIO_Pin = GPIO_Pin_6;
	GPIOInit_PA06_Struct.GPIO_Mode = GPIO_Mode_IN_PU;
	GPIOInit_PA06_Struct.GPIO_DriveLevel = 0;
	GPIO_Init(GPIOA,&GPIOInit_PA06_Struct);/*SCL0B端口初始化*/
	RCC_APB0PeriphClockCmd(RCC_APB0Periph_TWI0, ENABLE);
	/*Init Struct*/TWI_InitTypeDef TWI_InitStruct;
	TWI_InitStruct.TWI_Ack = TWI_Ack_Enable;
	TWI_InitStruct.TWI_Prescaler = TWI_PRESCALER_2048;
	TWI_InitStruct.TWI_Stretch = TWI_Stretch_Disable;
	TWI_InitStruct.TWI_SlaveAdress = 0x01;
	TWI_InitStruct.TWI_GeneralCall = TWI_GeneralCall_Disable;
	TWI_Init(TWI0, &TWI_InitStruct);
	TWI_PinRemapConfig(TWI0,TWI_PinRemap_B);
	/*INT*/TWI_ITConfig(TWI0,TWI_IT_INT,ENABLE);
	/*DMA_TX*/TWI_DMACmd(TWI0,TWI_DMAReq_TX,DISABLE);
	/*DMA_RX*/TWI_DMACmd(TWI0,TWI_DMAReq_RX,DISABLE);
	/*Init Struct*/NVIC_SetPriority(TWI0_IRQn,3);/*TWI0*/
	NVIC_EnableIRQ(TWI0_IRQn);
	TWI_Cmd(TWI0,ENABLE);
	/*<Generated by EasyCodeCube end>*/		
}

/**
  * @brief TWI1 init
  * @note 
  * @param
  */
void SC_TWI1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}


/**
  * @brief BTM init
  * @note 
  * @param
  */
void SC_BTM_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}


/**
  * @brief CRC init
  * @note 
  * @param
  */
void SC_CRC_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA0 init
  * @note 
  * @param
  */
void SC_DMA0_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA1 init
  * @note 
  * @param
  */
void SC_DMA1_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}
#if defined (SC32f10xx)

/**
  * @brief DMA2 init
  * @note 
  * @param
  */
void SC_DMA2_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief DMA3 init
  * @note 
  * @param
  */
void SC_DMA3_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}
#endif

/**
  * @brief WDT init
  * @note 
  * @param
  */
void SC_WDT_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief LCD init
  * @note 
  * @param
  */
void SC_LCD_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief SC_LED_Init
  * @note 
  * @param
  */
void SC_LED_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/
}

/**
  * @brief ACMP init
  * @note 
  * @param
  */
void SC_ACMP_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}

/**
  * @brief PWR init
  * @note 
  * @param
  */
void SC_PWR_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/	
}
#if defined (SC32f12xx)

/**
  * @brief OP init
  * @note 
  * @param
  */
void SC_OP_Init(void)
{
	/*<Generated by EasyCodeCube begin>*/
    //Forbid editing areas between the labels !!!
	/*<Generated by EasyCodeCube end>*/		
}

#endif





























