/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         SysFunVarDefine.c
  * @author	 
  * @version 	
  * @date	
  * @brief	         Store var control and function control define
  * @details         
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#include "SC_Init.h"
#include "SC_it.h"
#include "..\Drivers\SCDriver_list.h"
#include "HeadFiles\SysFunVarDefine.h"
#include "OLEDFONT.h"
#include "string.h"
//**********************************************************************
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
volatile unsigned char TWI0Flag = 0;
unsigned char TWI0SendData = 0;
unsigned char US0_UART_ReceiveData = 0;
 void delay(uint16_t cnt)
{
    /*<UserCodeStart>*//*<SinOne-Tag><65>*/
    while(cnt--);
    
    /*<UserCodeEnd>*//*<SinOne-Tag><65>*/
}
////清屏
 void OLED_Clear(void)
{
    /*<UserCodeStart>*//*<SinOne-Tag><66>*/
    uint8_t i,n;
    for(i=0;i<8;i++)  
    {  
        OLED_WR_Byte (0xb0+i,OLED_CMD);    
        OLED_WR_Byte (0x00,OLED_CMD);      
        OLED_WR_Byte (0x10,OLED_CMD);     
        for (n=0;n<128;n++)
        {
            OLED_WR_Byte(0,OLED_DATA); 
        }
    }
    
    /*<UserCodeEnd>*//*<SinOne-Tag><66>*/
}
////OLED屏幕背景正常/反色显示
 void OLED_ColorTurn(uint8_t ColorValue)
{
    /*<UserCodeStart>*//*<SinOne-Tag><67>*/
    if (ColorValue==0)
     {
         OLED_WR_Byte(0xA6,OLED_CMD);
     }
     if (ColorValue==1)
     {
         OLED_WR_Byte(0xA7,OLED_CMD);
     }
    
    /*<UserCodeEnd>*//*<SinOne-Tag><67>*/
}
////OLED显示关闭
 void OLED_Display_Off(void)
{
    /*<UserCodeStart>*//*<SinOne-Tag><69>*/
    OLED_WR_Byte(0X8D,OLED_CMD);
    OLED_WR_Byte(0X10,OLED_CMD);
    OLED_WR_Byte(0XAE,OLED_CMD);
    
    /*<UserCodeEnd>*//*<SinOne-Tag><69>*/
}
////OLED显示打开
 void OLED_Display_On(void)
{
    /*<UserCodeStart>*//*<SinOne-Tag><70>*/
    OLED_WR_Byte(0X8D,OLED_CMD);
     OLED_WR_Byte(0X14,OLED_CMD);
     OLED_WR_Byte(0XAF,OLED_CMD);
    
    /*<UserCodeEnd>*//*<SinOne-Tag><70>*/
}
////OLED屏幕背景正常/反转显示
 void OLED_DisplayTurn(uint8_t TurnValue)
{
    /*<UserCodeStart>*//*<SinOne-Tag><71>*/
     if (TurnValue==0)
     {
         OLED_WR_Byte(0xC8,OLED_CMD);
         OLED_WR_Byte(0xA1,OLED_CMD);
     }
     if(TurnValue==1)
     {
         OLED_WR_Byte(0xC0,OLED_CMD);
         OLED_WR_Byte(0xA0,OLED_CMD);
     }
    
    /*<UserCodeEnd>*//*<SinOne-Tag><71>*/
}
////初始化OLED配置
 void OLED_Init(void)
{
    /*<UserCodeStart>*//*<SinOne-Tag><72>*/
     OLED_WR_Byte(0xAE,OLED_CMD);
     OLED_WR_Byte(0x00,OLED_CMD);
     OLED_WR_Byte(0x10,OLED_CMD);
     OLED_WR_Byte(0x40,OLED_CMD);
     OLED_WR_Byte(0xb8,OLED_CMD);
  
     OLED_WR_Byte(0xa1,OLED_CMD);
     OLED_WR_Byte(0xa6,OLED_CMD);
     OLED_WR_Byte(0xa8,OLED_CMD);
     OLED_WR_Byte(0x3f,OLED_CMD);
     OLED_WR_Byte(0xc8,OLED_CMD);
     OLED_WR_Byte(0xd3,OLED_CMD);
     OLED_WR_Byte(0x00,OLED_CMD);
     OLED_WR_Byte(0xd5,OLED_CMD);
     OLED_WR_Byte(0x80,OLED_CMD);
     OLED_WR_Byte(0xd8,OLED_CMD);
     OLED_WR_Byte(0x05,OLED_CMD);
     OLED_WR_Byte(0xd9,OLED_CMD);
     OLED_WR_Byte(0xf1,OLED_CMD);
     OLED_WR_Byte(0xda,OLED_CMD);
     OLED_WR_Byte(0x12,OLED_CMD);
     OLED_WR_Byte(0xdb,OLED_CMD);
     OLED_WR_Byte(0x30,OLED_CMD);
     OLED_WR_Byte(0x8d,OLED_CMD);
     OLED_WR_Byte(0x14,OLED_CMD);
     OLED_WR_Byte(0xaf,OLED_CMD);
     OLED_Clear();
     OLED_WR_Byte(0xAF,OLED_CMD);
     OLED_ColorTurn(0);
     OLED_DisplayTurn(0);
     OLED_Display_Off();
     OLED_Display_On();
    
    
    /*<UserCodeEnd>*//*<SinOne-Tag><72>*/
}
////设置输入数据坐标x列：0~127  y行（页）：0~6
 void OLED_Set_Pos(uint8_t x,uint8_t y)
{
    /*<UserCodeStart>*//*<SinOne-Tag><73>*/
     OLED_WR_Byte(0xb0+y,OLED_CMD);
     OLED_WR_Byte(((x&0xf0)>>4)|0x10,OLED_CMD);
     OLED_WR_Byte((x&0x0f),OLED_CMD);
    
    /*<UserCodeEnd>*//*<SinOne-Tag><73>*/
}
/******************************************************************************************************
 *在指定位置显示一个字节数据，输入数据从高到低显示x列：0~127  y行（页）：0~6 input输入的
 *字节数据
 ******************************************************************************************************/
 void OLED_ShowByte(uint8_t x,uint8_t y,uint8_t input)
{
    /*<UserCodeStart>*//*<SinOne-Tag><74>*/
	   OLED_ShowByte( x+i,y+j ,image[width*j+i]);
		 }
	 }
}
//随机数字显示
void OLED_shownumber(uint8_t x,uint8_t y,uint8_t k)
{
uint8_t values[4]; 
char displayStr[100];
uint8_t j;
char temp[100];
 if (k >= 1000)
	 {      
        values[0] = k / 1000; 
	      values[1] = (k% 1000) / 100;
	      values[2] = (k / 10) % 10;
	      values[3] = k % 10;
		 for (j = 0; j < 4; j++) 
         {
        sprintf(temp, "%d", values[j]);  
					 displayStr[0] = '\0';
        strcat(displayStr, temp); 
				 } 
     OLED_Showstring(0,0,displayStr);
    }
  else
		{ if (k >= 100)
	 {       
	      values[0] = k / 100;
	      values[1] = (k / 10) % 10;
	      values[2] = k % 10;
		 for (j = 0; j < 3; j++) 
         {
        sprintf(temp, "%d", values[j]);  
	    displayStr[0] = '\0';
        strcat(displayStr, temp);
	     } 
     OLED_Showstring(0,0,displayStr);
    }
		 else
		{ if (k >= 10)
	 {      
        values[0] = (k / 10) % 10;
	      values[1] = k % 10;
		 for (j = 0; j < 2; j++) 
         {
        sprintf(temp, "%d", values[j]); 
         displayStr[0] = '\0';					 
        strcat(displayStr, temp); 
				 } 
     OLED_Showstring(0,0,displayStr);
    }
	 else
		{ if (k >= 1)
	 {      
        values[0] =  k % 10;
		 for (j = 0; j < 1; j++) 
         {
        sprintf(temp, "%d", values[j]);  
					 displayStr[0] = '\0';
        strcat(displayStr, temp); 
				 } 
     OLED_Showstring(0,0,displayStr);
    }
	 else
		{ if (k == 0)
	 {      
        values[0] =  0;
		  for (j = 0; j < 1; j++) 
         {
        sprintf(temp, "%d", values[j]);  
        strcat(displayStr, temp); } 
     OLED_Showstring(0,0,displayStr);
   }		 
}				 
}		
}		
}
	
}
//定义一个检索和按键的结构体
typedef struct
{
	uint8_t CurrentNum;	//当前索引序号:页码
	uint8_t Enter;		//确认键
	uint8_t above;    //上一个
	uint8_t Next;		//下一个
	uint8_t left;   //左一个
	uint8_t right;   //右一个
	uint8_t Return;		//返回键
	void (*Current_Operation)(void);//当前操作(函数指针)
}Menu_table_t;
//定义有关信息的结构体
struct RTC_CLOCK
{
		uint32_t year;
	  uint32_t mon;
	  uint32_t day;
		uint32_t hour;
		uint32_t min;
	  uint32_t sec;
		uint32_t week;
};
extern struct RTC_CLOCK rtc_clock;
//一级菜单
void Menu_Interface(void)
{
	char buff[50];
	
	//RTC_Get_StdTime(RTC_GetCounter());
	
	sprintf(buff,"%0.2d:%0.2d:%0.2d",rtc_clock.hour, rtc_clock.min, rtc_clock.sec);
	OLED_Showstring(16, 4,buff);
	
	sprintf(buff,"%0.4d-%0.2d-%0.2d",rtc_clock.year,rtc_clock.mon,rtc_clock.day);
	OLED_Showstring(16, 2, buff);
	
}
//二级界面显示内容
void Function_Interfaceset1(void)
{
	OLED_Showchar(0,0,'*');
	OLED_Showchinese(8,0,"闹钟设置");
	OLED_Showchinese(8,2,"日期设置");
	OLED_Showchinese(8,4,"时间设置");
}
void Function_Interfaceset2(void)
{
	OLED_Showchar(0,2,'*');
	OLED_Showchinese(8,0,"闹钟设置");
	OLED_Showchinese(8,2,"日期设置");
	OLED_Showchinese(8,4,"时间设置");
}
void Function_Interfaceset3(void)
{
	OLED_Showchar(0,4,'*');
	OLED_Showchinese(8,0,"闹钟设置");
	OLED_Showchinese(8,2,"日期设置");
	OLED_Showchinese(8,4,"时间设置");
	
}
//三级界面显示
//闹钟设置的三级显示
void Function_Interfacealarmclock1(void)//闹钟设置
{
	OLED_Showchar(0,0,'*');
	OLED_Showchinese(8,0,"闹钟一");
	OLED_Showchinese(8,2,"闹钟二");
	OLED_Showchinese(8,4,"闹钟三");
	
}
void Function_Interfacealarmclock2(void)//闹钟设置
{
	OLED_Showchar(0,2,'*');
	OLED_Showchinese(8,0,"闹钟一");
	OLED_Showchinese(8,2,"闹钟二");
	OLED_Showchinese(8,4,"闹钟三");
	
}
void Function_Interfacealarmclock3(void)//闹钟设置
{
	OLED_Showchar(0,4,'*');
	OLED_Showchinese(8,0,"闹钟一");
	OLED_Showchinese(8,2,"闹钟二");
	OLED_Showchinese(8,4,"闹钟三");
	
}
//日期设置的三级显示
void Function_Interfaceday1(void)//日期设置
{
	OLED_showimage(24,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.4d-%0.2d-%0.2d",rtc_clock.year,rtc_clock.mon,rtc_clock.day);
	OLED_Showstring(16, 2, buff);
	
}
void Function_Interfaceday2(void)//日期设置
{
	OLED_showimage(56,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.4d-%0.2d-%0.2d",rtc_clock.year,rtc_clock.mon,rtc_clock.day);
	OLED_Showstring(16, 2,  buff);
	
}
void Function_Interfaceday3(void)//日期设置
{
	OLED_showimage(80,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.4d-%0.2d-%0.2d",rtc_clock.year,rtc_clock.mon,rtc_clock.day);
	OLED_Showstring(16, 2, buff);
}
//时间的三级设置
void Function_Interfacetime1(void)//时间设置
{
	OLED_showimage(24,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.2d:%0.2d:%0.2d",rtc_clock.hour, rtc_clock.min, rtc_clock.sec);
	OLED_Showstring(16, 2, buff);
	
}
void Function_Interfacetime2(void)//时间设置
{
	OLED_showimage(56,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.2d:%0.2d:%0.2d",rtc_clock.hour, rtc_clock.min, rtc_clock.sec);
	OLED_Showstring(16, 2,  buff);
	
}
void Function_Interfacetime3(void)//时间设置
{
	OLED_showimage(80,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.2d:%0.2d:%0.2d",rtc_clock.hour, rtc_clock.min, rtc_clock.sec);
	OLED_Showstring(16, 2, buff);
}
uint8_t taskIndex = 0;	//初始任务
//任务调度表
Menu_table_t taskTable[] =
{
    //菜单界面函数 -- 一级界面
    {0, 1, 0, 0, 0,0,1, Menu_Interface}, 
    //功能界面函数 -- 二级界面
    {1, 4, 3, 2, 0,0,0, Function_Interfaceset1},
    {2, 7, 1, 3, 0,0,0, Function_Interfaceset2},
    {3, 10, 2, 1, 0,0,0, Function_Interfaceset3},
		//闹钟设置界面--三级函数
		{4, 4, 6, 5, 1,0,0, Function_Interfacealarmclock1},
    {5, 5, 4, 6, 1,0,0, Function_Interfacealarmclock2},
    {6, 6, 5, 4, 1,0,0, Function_Interfacealarmclock3},
	   //设置日期界面--三级函数
		{7, 7, 7, 7, 2,9, 8, Function_Interfaceday1},
    {8, 8, 8, 8, 2,7, 9, Function_Interfaceday2},
    {9, 9, 9, 9, 2,8, 7, Function_Interfaceday3},
		 //设置时间界面--三级函数
		{10, 10, 10, 10, 3,12, 11, Function_Interfacetime1},
    {11, 11, 11, 11, 3,10, 12, Function_Interfacetime2},
    {12, 12, 12, 12, 3,11, 10, Function_Interfacetime3},
};
void OLED_showlight(uint8_t m)
{
	OLED_WR_Byte(0X81,OLED_CMD);
	OLED_WR_Byte(m,OLED_CMD);
}
    /*<UserCodeEnd>*//*<SinOne-Tag><74>*/
}
////向OLED写入一个字节命令/数据dat，想要发送的一字节数据mode 0：命令  1:数据
 void OLED_WR_Byte(uint8_t dat,uint8_t mode)
{
    /*<UserCodeStart>*//*<SinOne-Tag><75>*/
     TWI_Start();
     TWI_SendByte(0x78);
     if (mode)
     {
         TWI_SendByte(0x40);
     }
     else
     {
         TWI_SendByte(0x00);
     }
     TWI_SendByte(dat);
     TWI_Stop();
    
    /*<UserCodeEnd>*//*<SinOne-Tag><75>*/
}
////发送一字节数据 SendByte：需要发送的数据
 void TWI_SendByte(uint8_t SendByte)
{
    /*<UserCodeStart>*//*<SinOne-Tag><78>*/
     TWI_SendData(TWI0,SendByte);
     while (!TWI0Flag);
     TWI0Flag = 0;
    
    /*<UserCodeEnd>*//*<SinOne-Tag><78>*/
}
////产生起始条件
 void TWI_Start(void)
{
    /*<UserCodeStart>*//*<SinOne-Tag><79>*/
    TWI_GenerateSTART(TWI0,ENABLE);
    while(!TWI0Flag);
    TWI0Flag = 0;
    delay(200); 
    
    /*<UserCodeEnd>*//*<SinOne-Tag><79>*/
}
////TWI主机模式停止位
 void TWI_Stop(void)
{
    /*<UserCodeStart>*//*<SinOne-Tag><80>*/
    TWI_GenerateSTOP(TWI0,ENABLE);
    delay(1300);
    
    /*<UserCodeEnd>*//*<SinOne-Tag><80>*/
}
/*************************************.Generated by EasyCodeCube.************************************/
//显示字符函数
void OLED_Showchar(uint8_t x,uint8_t y,char Char)
{  
	
   for(int i=0;i<8;i++)
		 { 
	   OLED_ShowByte( x+i,y,chararraychar8x16[Char - '!'][i]);
		 }
		 for(int i=0;i<8;i++)
		 { 
	   OLED_ShowByte( x+i,y+1,chararraychar8x16[Char - '!'][i+8]);
		  }    
}

//显示字符串
void OLED_Showstring(uint8_t x,uint8_t y,char *String)
{  	
   for(uint8_t i=0;String[i] != '\0';i++)
		 {
	   OLED_Showchar( x+i*8 ,y,String[i]);
		 }
	 
}

//显示多个汉字
void OLED_Showchinese(uint8_t x,uint8_t y,char *chinese)
{   char siglechinese[3]={0};
    uint8_t pchinese = 0;
    uint8_t pindex;
    uint8_t j=0;
    for(uint8_t i=0;chinese[i] != '\0';i++)
{
	siglechinese [pchinese]=chinese[i];
	pchinese++;
	if(pchinese >= 2)
	{
		pchinese = 0;
		
		for(pindex =0;strcmp(chararraychinese[pindex].index," ") != 0;pindex++)
		{
			if (strcmp(chararraychinese[pindex].index,siglechinese ) ==0)
			{
				break;
			}	
		}
		OLED_showimage(x+(j*16),y,16,2,chararraychinese[pindex].data);
		j++;
	}
}
}

//显示图案
void OLED_showimage(uint8_t x,uint8_t y,uint8_t width,uint8_t height, uint8_t *image)
{
	for(uint8_t j=0;j<height;j++)
	{
	for(int i=0;i<width;i++)
	   OLED_ShowByte( x+i,y+j ,image[width*j+i]);
		 }
	 }
}
//随机数字显示
void OLED_shownumber(uint8_t x,uint8_t y,uint8_t k)
{
uint8_t values[4]; 
char displayStr[100];
uint8_t j;
char temp[100];
 if (k >= 1000)
	 {      
        values[0] = k / 1000; 
	      values[1] = (k% 1000) / 100;
	      values[2] = (k / 10) % 10;
	      values[3] = k % 10;
		 for (j = 0; j < 4; j++) 
         {
        sprintf(temp, "%d", values[j]);  
					 displayStr[0] = '\0';
        strcat(displayStr, temp); 
				 } 
     OLED_Showstring(0,0,displayStr);
    }
  else
		{ if (k >= 100)
	 {       
	      values[0] = k / 100;
	      values[1] = (k / 10) % 10;
	      values[2] = k % 10;
		 for (j = 0; j < 3; j++) 
         {
        sprintf(temp, "%d", values[j]);  
	    displayStr[0] = '\0';
        strcat(displayStr, temp);
	     } 
     OLED_Showstring(0,0,displayStr);
    }
		 else
		{ if (k >= 10)
	 {      
        values[0] = (k / 10) % 10;
	      values[1] = k % 10;
		 for (j = 0; j < 2; j++) 
         {
        sprintf(temp, "%d", values[j]); 
         displayStr[0] = '\0';					 
        strcat(displayStr, temp); 
				 } 
     OLED_Showstring(0,0,displayStr);
    }
	 else
		{ if (k >= 1)
	 {      
        values[0] =  k % 10;
		 for (j = 0; j < 1; j++) 
         {
        sprintf(temp, "%d", values[j]);  
					 displayStr[0] = '\0';
        strcat(displayStr, temp); 
				 } 
     OLED_Showstring(0,0,displayStr);
    }
	 else
		{ if (k == 0)
	 {      
        values[0] =  0;
		  for (j = 0; j < 1; j++) 
         {
        sprintf(temp, "%d", values[j]);  
        strcat(displayStr, temp); } 
     OLED_Showstring(0,0,displayStr);
   }		 
}				 
}		
}		
}
	
}
//定义一个检索和按键的结构体
typedef struct
{
	uint8_t CurrentNum;	//当前索引序号:页码
	uint8_t Enter;		//确认键
	uint8_t above;    //上一个
	uint8_t Next;		//下一个
	uint8_t left;   //左一个
	uint8_t right;   //右一个
	uint8_t Return;		//返回键
	void (*Current_Operation)(void);//当前操作(函数指针)
}Menu_table_t;

//定义有关信息的结构体
struct RTC_CLOCK
{
		uint32_t year;
	  uint32_t mon;
	  uint32_t day;
		uint32_t hour;
		uint32_t min;
	  uint32_t sec;
		uint32_t week;
};
extern struct RTC_CLOCK rtc_clock;
//一级菜单

void Menu_Interface(void)
{
	char buff[50];
	
	//RTC_Get_StdTime(RTC_GetCounter());
	
	sprintf(buff,"%0.2d:%0.2d:%0.2d",rtc_clock.hour, rtc_clock.min, rtc_clock.sec);
	OLED_Showstring(16, 4,buff);
	
	sprintf(buff,"%0.4d-%0.2d-%0.2d",rtc_clock.year,rtc_clock.mon,rtc_clock.day);
	OLED_Showstring(16, 2, buff);
	
}


//二级界面显示内容
void Function_Interfaceset1(void)
{
	OLED_Showchar(0,0,'*');
	OLED_Showchinese(8,0,"闹钟设置");
	OLED_Showchinese(8,2,"日期设置");
	OLED_Showchinese(8,4,"时间设置");
}
void Function_Interfaceset2(void)
{
	OLED_Showchar(0,2,'*');
	OLED_Showchinese(8,0,"闹钟设置");
	OLED_Showchinese(8,2,"日期设置");
	OLED_Showchinese(8,4,"时间设置");
}
void Function_Interfaceset3(void)
{
	OLED_Showchar(0,4,'*');
	OLED_Showchinese(8,0,"闹钟设置");
	OLED_Showchinese(8,2,"日期设置");
	OLED_Showchinese(8,4,"时间设置");
	
}
//三级界面显示
//闹钟设置的三级显示
void Function_Interfacealarmclock1(void)//闹钟设置
{
	OLED_Showchar(0,0,'*');
	OLED_Showchinese(8,0,"闹钟一");
	OLED_Showchinese(8,2,"闹钟二");
	OLED_Showchinese(8,4,"闹钟三");
	
}
void Function_Interfacealarmclock2(void)//闹钟设置
{
	OLED_Showchar(0,2,'*');
	OLED_Showchinese(8,0,"闹钟一");
	OLED_Showchinese(8,2,"闹钟二");
	OLED_Showchinese(8,4,"闹钟三");
	
}
void Function_Interfacealarmclock3(void)//闹钟设置
{
	OLED_Showchar(0,4,'*');
	OLED_Showchinese(8,0,"闹钟一");
	OLED_Showchinese(8,2,"闹钟二");
	OLED_Showchinese(8,4,"闹钟三");
	
}
//日期设置的三级显示


void Function_Interfaceday1(void)//日期设置
{
	OLED_showimage(24,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.4d-%0.2d-%0.2d",rtc_clock.year,rtc_clock.mon,rtc_clock.day);
	OLED_Showstring(16, 2, buff);
	
}
void Function_Interfaceday2(void)//日期设置
{
	OLED_showimage(56,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.4d-%0.2d-%0.2d",rtc_clock.year,rtc_clock.mon,rtc_clock.day);
	OLED_Showstring(16, 2,  buff);
	
}
void Function_Interfaceday3(void)//日期设置
{
	OLED_showimage(80,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.4d-%0.2d-%0.2d",rtc_clock.year,rtc_clock.mon,rtc_clock.day);
	OLED_Showstring(16, 2, buff);
}

//时间的三级设置
void Function_Interfacetime1(void)//时间设置
{
	OLED_showimage(24,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.2d:%0.2d:%0.2d",rtc_clock.hour, rtc_clock.min, rtc_clock.sec);
	OLED_Showstring(16, 2, buff);
	
}
void Function_Interfacetime2(void)//时间设置
{
	OLED_showimage(56,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.2d:%0.2d:%0.2d",rtc_clock.hour, rtc_clock.min, rtc_clock.sec);
	OLED_Showstring(16, 2,  buff);
	
}
void Function_Interfacetime3(void)//时间设置
{
	OLED_showimage(80,4,16,2, dingwei);
	char buff[50];
	sprintf(buff,"%0.2d:%0.2d:%0.2d",rtc_clock.hour, rtc_clock.min, rtc_clock.sec);
	OLED_Showstring(16, 2, buff);
}

uint8_t taskIndex = 0;	//初始任务
//任务调度表
Menu_table_t taskTable[] =
{
    //菜单界面函数 -- 一级界面
    {0, 1, 0, 0, 0,0,1, Menu_Interface}, 
    //功能界面函数 -- 二级界面
    {1, 4, 3, 2, 0,0,0, Function_Interfaceset1},
    {2, 7, 1, 3, 0,0,0, Function_Interfaceset2},
    {3, 10, 2, 1, 0,0,0, Function_Interfaceset3},
		//闹钟设置界面--三级函数
		{4, 4, 6, 5, 1,0,0, Function_Interfacealarmclock1},
    {5, 5, 4, 6, 1,0,0, Function_Interfacealarmclock2},
    {6, 6, 5, 4, 1,0,0, Function_Interfacealarmclock3},
	   //设置日期界面--三级函数
		{7, 7, 7, 7, 2,9, 8, Function_Interfaceday1},
    {8, 8, 8, 8, 2,7, 9, Function_Interfaceday2},
    {9, 9, 9, 9, 2,8, 7, Function_Interfaceday3},
		 //设置时间界面--三级函数
		{10, 10, 10, 10, 3,12, 11, Function_Interfacetime1},
    {11, 11, 11, 11, 3,10, 12, Function_Interfacetime2},
    {12, 12, 12, 12, 3,11, 10, Function_Interfacetime3},
};
void OLED_showlight(uint8_t m)
{
	OLED_WR_Byte(0X81,OLED_CMD);
	OLED_WR_Byte(m,OLED_CMD);
}
