/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	CustomType.h
  * @author	 
  * @version 	
  * @date	
  * @brief	
  * @details 
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#ifndef CUSTOM_TYPE_H
    #define CUSTOM_TYPE_H
#endif	

#define OLED_CMD 0
#define OLED_DATA 1
/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!

/*************************************.Generated by EasyCodeCube.************************************/
