/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	         Function.h
  * @author	 
  * @version 	
  * @date	
  * @brief	         Store quote of the function 
  * @details 
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#ifndef FUNCTION_H
 #define FUNCTION_H
#include "SC_it.h"
#endif	

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
extern void delay(uint16_t cnt);
extern void OLED_Clear(void);
extern void OLED_ColorTurn(uint8_t ColorValue);
extern void OLED_Display_Off(void);
extern void OLED_Display_On(void);
extern void OLED_DisplayTurn(uint8_t TurnValue);
extern void OLED_Init(void);
extern void OLED_Set_Pos(uint8_t x,uint8_t y);
extern void OLED_ShowByte(uint8_t x,uint8_t y,uint8_t input);
extern void OLED_WR_Byte(uint8_t dat,uint8_t mode);
extern void TWI_SendByte(uint8_t SendByte);
extern void TWI_Start(void);
extern void TWI_Stop(void);
extern void IcResourceInit(void);
/*************************************.Generated by EasyCodeCube.************************************/
