/**
 *****************************************************************************************************
  * @copyright	(c)  Shenzhen Saiyuan Microelectronics Co., Ltd
  * @file	SC_itExtern.h
  * @author	 
  * @version 	
  * @date	
  * @brief	store extern var code
  * @details 
 *****************************************************************************************************
 * @attention
 *
 *****************************************************************************************************
 */
#ifndef SC_IT_EXTERN_H
    #define SC_IT_EXTERN_H
#include "SysFunVarDefine.h"
#endif

/**************************************Generated by EasyCodeCube*************************************/
//Forbid editing areas between the labels !!!
extern volatile unsigned char TWI0Flag;
extern unsigned char TWI0SendData;
extern unsigned char US0_UART_ReceiveData;
/*************************************.Generated by EasyCodeCube.************************************/
